site_name: Bank Documentation
theme:
  name: readthedocs

markdown_extensions:
  - plantuml_markdown:
      server: https://www.plantuml.com/plantuml
      format: svg
  - md_in_html
  - toc

plugins:
  - search
